# Generated by Django 5.1.6 on 2025-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorattot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
